-- MySQL Script generated by MySQL Workbench
-- Thu May 25 19:26:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ticketsdb` ;

-- -----------------------------------------------------
-- Schema ticketsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketsdb` DEFAULT CHARACTER SET utf8 ;
USE `ticketsdb` ;

-- -----------------------------------------------------
-- Table `ticketsdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`user` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`user` (
  `user_id` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(100) NOT NULL,
  `user_phone` VARCHAR(100) NOT NULL,
  `user_gender` VARCHAR(10) NULL,
  `user_age` INT NULL,
  `user_email` VARCHAR(30) NULL,
  `user_avatar` VARCHAR(9999) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_phone_UNIQUE` (`user_phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`city` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`city` (
  `city_id` VARCHAR(100) NOT NULL,
  `city_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`cinema` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`cinema` (
  `cinema_id` VARCHAR(100) NOT NULL,
  `cinema_name` VARCHAR(100) NOT NULL,
  `cinema_address` VARCHAR(100) NULL,
  `cinema_phone` VARCHAR(100) NULL,
  `city_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cinema_id`),
  INDEX `fk_cinema_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_cinema_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `ticketsdb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`room` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`room` (
  `room_id` VARCHAR(100) NOT NULL,
  `room_name` VARCHAR(100) NOT NULL,
  `room_type` VARCHAR(100) NULL,
  `room_col` INT NOT NULL,
  `room_row` INT NOT NULL,
  `cinema_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_cinema1_idx` (`cinema_id` ASC),
  CONSTRAINT `fk_room_cinema1`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `ticketsdb`.`cinema` (`cinema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`movieType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`movieType` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`movieType` (
  `movie_type_id` VARCHAR(100) NOT NULL,
  `movie_type_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`movie_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`movie` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`movie` (
  `movie_id` VARCHAR(100) NOT NULL,
  `movie_name` VARCHAR(100) NOT NULL,
  `movie_release_date` VARCHAR(100) NULL,
  `movie_storyline` VARCHAR(1000) NULL,
  `movie_detail` VARCHAR(999) NULL,
  `movie_poster` VARCHAR(9999) NULL,
  `movie_avgScore` FLOAT NULL,
  `movie_isshow` TINYINT(1) NULL,
  `movie_type_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`movie_id`),
  INDEX `fk_movie_movieType1_idx` (`movie_type_id` ASC),
  CONSTRAINT `fk_movie_movieType1`
    FOREIGN KEY (`movie_type_id`)
    REFERENCES `ticketsdb`.`movieType` (`movie_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`showing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`showing` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`showing` (
  `showing_id` VARCHAR(100) NOT NULL,
  `showing_date` VARCHAR(100) NOT NULL,
  `room_id` VARCHAR(100) NOT NULL,
  `movie_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`showing_id`),
  INDEX `fk_show_room1_idx` (`room_id` ASC),
  INDEX `fk_show_movie1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_show_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `ticketsdb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_show_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `ticketsdb`.`movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`ticket` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`ticket` (
  `ticket_id` VARCHAR(100) NOT NULL,
  `ticket_seatColNum` INT NOT NULL,
  `ticket_seatRowNum` INT NULL,
  `ticket_price` FLOAT NOT NULL,
  `ticket_issold` TINYINT(1) NOT NULL,
  `showing_id` VARCHAR(100) NOT NULL,
  `user_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ticket_id`),
  INDEX `fk_ticket_show1_idx` (`showing_id` ASC),
  INDEX `fk_ticket_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ticket_show1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `ticketsdb`.`showing` (`showing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticketsdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`review` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`review` (
  `review_id` VARCHAR(100) NOT NULL,
  `review_content` VARCHAR(9999) NULL,
  `review_score` FLOAT NULL,
  `review_title` VARCHAR(100) NULL,
  `review_date` VARCHAR(100) NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `showing_id` VARCHAR(100) NOT NULL,
  `movie_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_review_user1_idx` (`user_id` ASC),
  INDEX `fk_review_show1_idx` (`showing_id` ASC),
  INDEX `fk_review_movie1_idx` (`movie_id` ASC),
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticketsdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_show1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `ticketsdb`.`showing` (`showing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `ticketsdb`.`movie` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketsdb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticketsdb`.`comment` ;

CREATE TABLE IF NOT EXISTS `ticketsdb`.`comment` (
  `comment_id` VARCHAR(100) NOT NULL,
  `comment_title` VARCHAR(100) NULL,
  `comment_content` VARCHAR(1000) NULL,
  `comment_date` VARCHAR(100) NULL,
  `cinema_id` VARCHAR(100) NOT NULL,
  `user_id` VARCHAR(100) NOT NULL,
  `showing_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comment_cinema1_idx` (`cinema_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_show1_idx` (`showing_id` ASC),
  CONSTRAINT `fk_comment_cinema1`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `ticketsdb`.`cinema` (`cinema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ticketsdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_show1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `ticketsdb`.`showing` (`showing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
